// Package marketdatarecovery implements a snapshot-plus-delta order-book
// recovery state machine.
//
// Deltas carry absolute quantities as of LastSequence and an inclusive
// [FirstSequence, LastSequence] range. This resembles common exchange depth
// feeds, but every venue adapter must translate its own sequence contract into
// these semantics. Epoch may be supplied by the venue or generated by the
// adapter for one subscription/recovery generation.
package marketdatarecovery

import (
	"errors"
	"fmt"
	"sort"
)

var (
	ErrGap          = errors.New("market data sequence gap")
	ErrEpochChanged = errors.New("market data epoch changed")
)

type State string

const (
	StateIdle           State = "IDLE"
	StateBuffering      State = "BUFFERING"
	StateLive           State = "LIVE"
	StateResyncRequired State = "RESYNC_REQUIRED"
)

type Side string

const (
	Bid Side = "BID"
	Ask Side = "ASK"
)

// Level is an absolute quantity at Price. Quantity zero deletes the level.
type Level struct {
	Price    int64 `json:"price"`
	Quantity int64 `json:"quantity"`
}

type Snapshot struct {
	Epoch    string  `json:"epoch"`
	Sequence uint64  `json:"sequence"`
	Bids     []Level `json:"bids"`
	Asks     []Level `json:"asks"`
}

type Delta struct {
	Epoch         string  `json:"epoch"`
	FirstSequence uint64  `json:"first_sequence"`
	LastSequence  uint64  `json:"last_sequence"`
	Bids          []Level `json:"bids"`
	Asks          []Level `json:"asks"`
}

type View struct {
	State    State   `json:"state"`
	Epoch    string  `json:"epoch,omitempty"`
	Sequence uint64  `json:"sequence,omitempty"`
	Bids     []Level `json:"bids"`
	Asks     []Level `json:"asks"`
}

type Book struct {
	state    State
	epoch    string
	sequence uint64
	bids     map[int64]int64
	asks     map[int64]int64
	buffered []Delta
}

func New() *Book {
	return &Book{
		state: StateIdle,
		bids:  make(map[int64]int64),
		asks:  make(map[int64]int64),
	}
}

func (b *Book) State() State {
	return b.state
}

// BeginResync discards the local view and starts buffering stream deltas before
// a snapshot is fetched. A gap is not repaired by guessing or skipping.
func (b *Book) BeginResync() {
	b.state = StateBuffering
	b.epoch = ""
	b.sequence = 0
	b.bids = make(map[int64]int64)
	b.asks = make(map[int64]int64)
	b.buffered = nil
}

// OnDelta buffers deltas during recovery and applies them in live mode.
// A stale/duplicate range is ignored only when it is entirely at or below the
// already-applied sequence.
func (b *Book) OnDelta(delta Delta) error {
	if err := validateDelta(delta); err != nil {
		if b.state == StateBuffering || b.state == StateLive {
			return b.requireResync(fmt.Errorf("invalid market data delta: %w", err))
		}
		return err
	}

	switch b.state {
	case StateBuffering:
		b.buffered = append(b.buffered, cloneDelta(delta))
		return nil
	case StateLive:
		if delta.Epoch != b.epoch {
			return b.requireResync(ErrEpochChanged)
		}
		if delta.LastSequence <= b.sequence {
			return nil
		}
		next := b.sequence + 1
		if delta.FirstSequence > next {
			return b.requireResync(fmt.Errorf(
				"%w: have=%d next_range=[%d,%d]",
				ErrGap,
				b.sequence,
				delta.FirstSequence,
				delta.LastSequence,
			))
		}
		applyLevels(b.bids, delta.Bids)
		applyLevels(b.asks, delta.Asks)
		b.sequence = delta.LastSequence
		return nil
	case StateIdle:
		return errors.New("begin resync before accepting deltas")
	case StateResyncRequired:
		return errors.New("resync is required before accepting deltas")
	default:
		return fmt.Errorf("unsupported state %q", b.state)
	}
}

// InstallSnapshot atomically installs a snapshot and bridges every buffered
// delta. The first non-stale delta must cover snapshot.Sequence+1; subsequent
// deltas must cover the next expected sequence.
func (b *Book) InstallSnapshot(snapshot Snapshot) error {
	if b.state != StateBuffering {
		return fmt.Errorf("cannot install snapshot while state=%s", b.state)
	}
	if err := validateSnapshot(snapshot); err != nil {
		return err
	}

	bids := make(map[int64]int64, len(snapshot.Bids))
	asks := make(map[int64]int64, len(snapshot.Asks))
	applyLevels(bids, snapshot.Bids)
	applyLevels(asks, snapshot.Asks)
	sequence := snapshot.Sequence

	for _, delta := range b.buffered {
		if delta.Epoch != snapshot.Epoch {
			return b.requireResync(fmt.Errorf(
				"%w: snapshot=%q delta=%q",
				ErrEpochChanged,
				snapshot.Epoch,
				delta.Epoch,
			))
		}
		if delta.LastSequence <= sequence {
			continue
		}
		next := sequence + 1
		if delta.FirstSequence > next {
			return b.requireResync(fmt.Errorf(
				"%w while bridging snapshot: have=%d next_range=[%d,%d]",
				ErrGap,
				sequence,
				delta.FirstSequence,
				delta.LastSequence,
			))
		}
		applyLevels(bids, delta.Bids)
		applyLevels(asks, delta.Asks)
		sequence = delta.LastSequence
	}

	b.state = StateLive
	b.epoch = snapshot.Epoch
	b.sequence = sequence
	b.bids = bids
	b.asks = asks
	b.buffered = nil
	return nil
}

func (b *Book) View() View {
	return View{
		State:    b.state,
		Epoch:    b.epoch,
		Sequence: b.sequence,
		Bids:     sortedLevels(b.bids, true),
		Asks:     sortedLevels(b.asks, false),
	}
}

func (b *Book) requireResync(err error) error {
	b.state = StateResyncRequired
	b.epoch = ""
	b.sequence = 0
	b.bids = make(map[int64]int64)
	b.asks = make(map[int64]int64)
	b.buffered = nil
	return err
}

func validateSnapshot(snapshot Snapshot) error {
	if snapshot.Epoch == "" {
		return errors.New("snapshot epoch is required")
	}
	if err := validateLevels("snapshot bids", snapshot.Bids); err != nil {
		return err
	}
	if err := validateLevels("snapshot asks", snapshot.Asks); err != nil {
		return err
	}
	return nil
}

func validateDelta(delta Delta) error {
	if delta.Epoch == "" {
		return errors.New("delta epoch is required")
	}
	if delta.FirstSequence == 0 || delta.LastSequence < delta.FirstSequence {
		return fmt.Errorf(
			"invalid delta range [%d,%d]",
			delta.FirstSequence,
			delta.LastSequence,
		)
	}
	if err := validateLevels("delta bids", delta.Bids); err != nil {
		return err
	}
	if err := validateLevels("delta asks", delta.Asks); err != nil {
		return err
	}
	return nil
}

func validateLevels(label string, levels []Level) error {
	seen := make(map[int64]struct{}, len(levels))
	for _, level := range levels {
		if level.Price <= 0 {
			return fmt.Errorf("%s contains non-positive price %d", label, level.Price)
		}
		if level.Quantity < 0 {
			return fmt.Errorf("%s contains negative quantity at price %d", label, level.Price)
		}
		if _, exists := seen[level.Price]; exists {
			return fmt.Errorf("%s contains duplicate price %d", label, level.Price)
		}
		seen[level.Price] = struct{}{}
	}
	return nil
}

func applyLevels(dst map[int64]int64, levels []Level) {
	for _, level := range levels {
		if level.Quantity == 0 {
			delete(dst, level.Price)
			continue
		}
		dst[level.Price] = level.Quantity
	}
}

func sortedLevels(source map[int64]int64, descending bool) []Level {
	out := make([]Level, 0, len(source))
	for price, quantity := range source {
		out = append(out, Level{Price: price, Quantity: quantity})
	}
	sort.Slice(out, func(i, j int) bool {
		if descending {
			return out[i].Price > out[j].Price
		}
		return out[i].Price < out[j].Price
	})
	return out
}

func cloneDelta(delta Delta) Delta {
	delta.Bids = append([]Level(nil), delta.Bids...)
	delta.Asks = append([]Level(nil), delta.Asks...)
	return delta
}
